//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEADGroupManagerSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCDADObjctDNPartial
    {
        public UCDADObjctDNPartial()
        {
            this.UCDADGroupAppRoles = new HashSet<UCDADGroupAppRole>();
        }
    
        public int UAODPID { get; set; }
        public string DNPartial { get; set; }
    
        public virtual ICollection<UCDADGroupAppRole> UCDADGroupAppRoles { get; set; }
    }
}
