//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEADGroupManagerSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGMGroup
    {
        public AGMGroup()
        {
            this.AGMManagers = new HashSet<AGMManager>();
            this.AGMMemberRequests = new HashSet<AGMMemberRequest>();
        }
    
        public System.Guid AGMGID { get; set; }
        public string ADGrpName { get; set; }
        public string ADGrpDN { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> MngrNtcLastSent { get; set; }
        public Nullable<bool> SendMgrReport { get; set; }
        public Nullable<bool> SendGrpReport { get; set; }
        public string ReportAdtlAddr { get; set; }
        public Nullable<int> DaysBtwnReport { get; set; }
        public Nullable<bool> SendHTMLRpt { get; set; }
        public Nullable<bool> SendProvisionRpts { get; set; }
        public Nullable<bool> MbrshpLimited { get; set; }
        public Nullable<int> MbrshpLimit { get; set; }
        public Nullable<bool> AD3AdminAcntOnly { get; set; }
        public string GrpDescription { get; set; }
        public Nullable<bool> GrpDescriptionAD { get; set; }
    
        public virtual ICollection<AGMManager> AGMManagers { get; set; }
        public virtual ICollection<AGMMemberRequest> AGMMemberRequests { get; set; }
    }
}
