//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEADGroupManagerSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGMManagerSnapShot_MgmtAssignment
    {
        public int AMSSMAID { get; set; }
        public int AMSSID { get; set; }
        public string ADGrpGUID { get; set; }
        public string ADGrpName { get; set; }
        public Nullable<System.DateTime> SSRptDate { get; set; }
    
        public virtual AGMManagerSnapShot AGMManagerSnapShot { get; set; }
    }
}
