//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEADGroupManagerSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGMManagerSnapShot
    {
        public AGMManagerSnapShot()
        {
            this.AGMManagerSnapShot_MgmtAssignment = new HashSet<AGMManagerSnapShot_MgmtAssignment>();
        }
    
        public int AMSSID { get; set; }
        public string KerbID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> SSRptDate { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual ICollection<AGMManagerSnapShot_MgmtAssignment> AGMManagerSnapShot_MgmtAssignment { get; set; }
    }
}
