//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEADGroupManagerSQL
{
    using System;
    
    public partial class AGMSDB_Mothra_UserAccnt
    {
        public string LOGINID { get; set; }
        public string MOTHRAID { get; set; }
        public string ACCTTYPE { get; set; }
        public string CLIENTTYPE { get; set; }
        public string CLIENTSTATUS { get; set; }
        public string DEPTCODE { get; set; }
        public string TITLECODE { get; set; }
        public string ACCTSTATUS { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
    }
}
