//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COEADGroupManagerSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCDADGroupAppRole
    {
        public UCDADGroupAppRole()
        {
            this.UCDADObjctDNPartials = new HashSet<UCDADObjctDNPartial>();
        }
    
        public int UUAARID { get; set; }
        public string RoleName { get; set; }
        public string RoleGroupDN { get; set; }
        public Nullable<bool> IsDeptRole { get; set; }
    
        public virtual ICollection<UCDADObjctDNPartial> UCDADObjctDNPartials { get; set; }
    }
}
